package co.edu.uniquindio.unimarket.modelo;

public enum Ciudad {
    ARMENIA, MANIZALES, BARRANQUILLA, BOGOTÁ, CARTAGENA, MEDELLÍN, CALI, PEREIRA, BUCARAMANGA, CÚCUTA, VILLAVICENCIO, IBAGUÉ, VALLEDUPAR, MONTERÍA, POPAYÁN, NEIVA, SINCELEJO, TUNJA, MANAURE, PALMIRA, SOLEDAD, DOSQUEBRADAS, FLORIDABLANCA, ITAGÜÍ, MALAMBO,  FUNZA, RIONEGRO, CARTAGO, MAICAO, GIRARDOT, ZIPAQUIRÁ, SABANETA, QUIBDÓ, TURBO, YUMBO, FLORENCIA, ENVIGADO, GIRON, MADRID, ACACÍAS, CHÍA, MOSQUERA, FUSAGASUGÁ,  YOPAL, PASTO
}
